#!/usr/bin/env bash
# script that configures a new Ubuntu machine

sudo apt-get -y update
sudo apt-get -y install nginx
sudo ufw allow "Nginx HTTP"
echo "Hello World!" | sudo tee /usr/share/nginx/html/index.html
echo "Hello World!" | sudo tee /var/www/html/index.nginx-debian.html
sudo service nginx start
