#!/usr/bin/env bash
# need to configure web-02 to be identical to web-01

sudo apt-get -y update
sudo apt-get -y install nginx
sudo ufw allow "Nginx HTTP"
sudo sed -i "11i\\\tadd_header X-Served-By $HOSTNAME;" /etc/nginx/nginx.conf
echo "Hello World!" | sudo tee /usr/share/nginx/html/index.html
echo "Hello World!" | sudo tee /var/www/html/index.nginx-debian.html
sudo service nginx start
