#!/usr/bin/env bash
# information about the school file

NAMEF="school"
if [ -e "$NAMEF" ]
then
    echo "$NAMEF file exists"
    if [ -s "$NAMEF" ]
    then
	echo "school file is not empty"
    else
	echo "school file is empty"
    fi
    if [ -f "$NAMEF" ]
    then
	echo "school is a regular file"
    fi
else
    echo "school file does not exist"
fi